- Assets/Scripts/FirstPersonController.cs
- Assets/Scripts/FirstPersonController.cs.meta
Add jump for player, gravity included in the script FirstPersonController. Is able to jump and use the camera movement script together.
> Add jump for player

- Assets/Scenes/Testing.unity
- Assets/Scripts/FirstPersonController.cs
- Assets/Scripts/FirstPersonController.cs.meta
Add walk functionality to navigate the world with the help of character controller
> Add walk for player

- Assets/Scripts/FirstPersonController.cs
Add run by utilizing Vector2 for calculating current speed. This makes it possible for the player to accelerate up to a certain speed. When no input is detected the player will instantly stop.
Setting a higher acceleration value will make the acceleration go faster due to the multiplication with Time.deltaTime.
> Add slower diagonal movement and deceleration

- Assets/Materials/Player.meta
- Assets/Materials/Player/HG_Haircap.004.mat
- Assets/Materials/Player/HG_Haircap.004.mat.meta
- Assets/Materials/Player/HG_Haircap_Alpha.004.mat
- Assets/Materials/Player/HG_Haircap_Alpha.004.mat.meta
- Assets/Materials/Player/HG_Haircards.009.mat
- Assets/Materials/Player/HG_Haircards.009.mat.meta
- Assets/Materials/Player/_HG_Eyes_Inner.005.mat
- Assets/Materials/Player/_HG_Eyes_Inner.005.mat.meta
- Assets/Materials/Player/_HG_Eyes_Outer_FAST.006.mat
- Assets/Materials/Player/_HG_Eyes_Outer_FAST.006.mat.meta
- Assets/Materials/Player/_HG_Skinny_Jeans.006.mat
- Assets/Materials/Player/_HG_Skinny_Jeans.006.mat.meta
- Assets/Materials/Player/_HG_Suede_Sneaker.005.mat
- Assets/Materials/Player/_HG_Suede_Sneaker.005.mat.meta
- Assets/Materials/Player/_HG_Sweater_2.005.mat
- Assets/Materials/Player/_HG_Sweater_2.005.mat.meta
- Assets/Materials/Player/_Human.005.mat
- Assets/Materials/Player/_Human.005.mat.meta
- Assets/Models/Player.meta
- Assets/Models/Player/Aaron.fbx.meta
- Assets/Prefabs/Player Aaron.prefab
- Assets/Prefabs/Player Aaron.prefab.meta
- Assets/Prefabs/PlayerAaron.prefab
- Assets/Prefabs/PlayerAaron.prefab.meta
- Assets/Scenes/Testing.unity
Add a model for the main character named Aaron.
Extracted some basic materials from the model, textures are not added yet.
Added all camera and player movement and tweaked the variables for the player then made a prefab for Player Aaron.
Solves #1
> Add main character Aaron

- Assets/Scenes/Testing.unity
- Assets/Scripts/FirstPersonController.cs
Add slope sliding using SphereCast to detect if the cast hits a slope.
A bit buggy when walking to the sides and looking at certain angles, player bouncing back and forth.
> Add slope sliding

- Assets/Scenes/Testing.unity
- Assets/Scripts/FirstPersonController.cs
Need to fix smoothness and change crouchSpeed.
> Add Crouch

- Assets/Prefabs/InventoryUI.prefab
- Assets/Prefabs/UI.prefab
- Assets/Scripts/FirstPersonController.cs
- Assets/Scripts/Inventory.cs
- Assets/Scripts/Item Scripts/Door.cs
- Assets/Scripts/PhotoCapture.cs
Add interaction with inventory and camera. Add comments to inventory script.
> Camera inventory

- Assets/Scenes/Testing.unity
- Assets/Scripts/EnemyController.cs
- Assets/Scripts/PhotoCapture.cs
In the testing scene, there are 3 positions that the enemy can teleport to. It chooses the one furthest away when an image is taken within distance.
> Enemy camera flash scare

- Assets/Scripts/Item Scripts/Battery.cs
- Assets/Scripts/Item Scripts/Key.cs
- Assets/Scripts/Item Scripts/Pill.cs
Items like the battery and pills now get despawned in multiplayer so the other player can not pick up the same item.
> Fix pickup items despawn

- Assets/Prefabs/ItemPolaroid.prefab
- Assets/Prefabs/NetworkManager.prefab
- Assets/Prefabs/Player/Player Aaron.prefab
- Assets/Scripts/PauseMenu.cs
- Assets/Scripts/PhotoCapture.cs
> Coop camera2.0

- Assets/Scenes/MainMenu.unity
- Assets/Scripts/CreateMenuScript.cs
- Assets/Scripts/IpPortInputScript.cs
- Assets/Scripts/SinglePlayerBtn.cs
- Assets/Scripts/SinglePlayerBtn.cs.meta
Singleplayer mode was broken, fixed it. Both singleplayer and multiplayer work now.
> Add single player menu logic.

- Assets/Materials/Dungeon Layout/Floor.mat
- Assets/Materials/Dungeon Layout/Wall.mat
- Assets/Scenes/Dungeon.unity
Update the dungeon position so that all players spawn within the map.
Move the ladders to the new correct location.
Fix the texture tiling with the new UV unwrap of the new model.
> Fix dungeon and ladder positions

- Assets/Materials/Dungeon Layout/Floor.mat
- Assets/Materials/Dungeon Layout/Wall.mat
Add a higher parkour room 
Add higher start and end pipes
Fix textures UV to use smaller material scaling/tiling
> Fix map height and materials

- Assets/Prefabs/Note.prefab
- Assets/Scenes/Testing.unity
- Assets/Scripts/Item Scripts/Note.cs
Notes which were not connected to the code lock puzzle had errors, no door was detected.
This is now fixed!
> Fix note which is not connected to door

- Assets/Prefabs/Button.prefab
- Assets/Prefabs/Puzzles.meta
- Assets/Prefabs/Puzzles/Puzzle 3.prefab
- Assets/Prefabs/Puzzles/Puzzle 3.prefab.meta
- Assets/Scenes/Dungeon.unity
Added a P3 puzzle and added it to the dungeon scene
Update the button prefab so the network stuff is in the root.
It's still missing the key 1 for the first door, so unlock that through the editor.
> Add P3 puzzle

- Assets/Scripts/Item Scripts/Door.cs
- Assets/Scripts/PuzzleInputController.cs
Fixed so no yellow errors, things still work
> Remove errors

- Assets/Scripts/Inventory.cs
- Assets/Scripts/PauseMenu.cs
- Assets/Scripts/keypadScript.cs
This is a bug fix, the mouse was invisible when the inventory was opened. This has been fixed.
> Fix inventory mouse

- Assets/Scripts/CameraMovement.cs
Add camera clamping based on the animation head rotation.
> Camera clamping based on animation.

- Assets/Scripts/FirstPersonController.cs
Remove hold crouch, players can only use toggle crouch on key C now.
Closes #171
> Remove hold crouch

- Assets/Scripts/PhotoCapture.cs
The image size can now be changed from the inspector.
> Fix polaroid image not centered for other sizes
